# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_customerdistribution_salerank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='小手'),
        ),
    ]
